@startuml

title __DATABASEUTIL's Class Diagram__\n

  package Twitter {
    package Twitter.DatabaseUtil {
      class DBConnection {
          {static} - connection : Connection
          {static} - DRIVER : String
          {static} - USER : String
          {static} - PASS : String
          {static} + getConnection()
      }
    }
  }
  

  package Twitter {
    package Twitter.DatabaseUtil {
      class DBController {
          {static} - statement : Statement
          {static} - resultSet : ResultSet
          {static} + searchQuery()
          {static} + updateQuery()
      }
    }
  }
  

  package Twitter {
    package Twitter.DatabaseUtil {
      class DataLoader {
          {static} + dataLoader : DataLoader
          ~ conn : Connection
          + DataLoader()
          - isImage()
          {static} + getDataLoader()
          + loadImage()
          + returnPerson()
          + returnFollow()
          + returnPostList()
          + returnFollowingPostList()
          + returnHashTags()
          + insertPost()
          + genericSearchQuery()
          + genericUpdateQuery()
          + checkIfFollows()
          + refresh()
          + retrieveAllUsers()
      }
    }
  }
  

  package Twitter {
    package Twitter.DatabaseUtil {
      enum FollowType {
        FOLLOWER
        FOLLOWING
      }
    }
  }
  

  package Twitter {
    package Twitter.DatabaseUtil {
      interface Facade {
          {abstract} + loadThisPerson()
      }
    }
  }
  

  package Twitter {
    package Twitter.DatabaseUtil {
      class PersonLoader {
          + loadThisPerson()
      }
    }
  }
  

  DataLoader +-down- FollowType
  PersonLoader -up-|> Facade


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
