CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(20) PRIMARY KEY,
    PASSWORD VARCHAR(20),
    SECURITYQ VARCHAR(20),
    DATECREATED DATE
);

CREATE TABLE ADMIN (
    USERNAME VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY(USERNAME) REFERENCES ACCOUNT(USERNAME)
);

CREATE TABLE PERSON (
    USERNAME VARCHAR(20) PRIMARY KEY,
    DATEJOINED VARCHAR(20),
    PROFILEIMAGE VARCHAR(200),
    FOREIGN KEY(USERNAME) REFERENCES ACCOUNT(USERNAME)
    ON DELETE CASCADE
);

CREATE TABLE FOLLOWER (
    /*Who is following me*/
    FOLLOWERUSERNAME VARCHAR(20),
    /*Me*/
    USERNAME VARCHAR(20),
    PRIMARY KEY(FOLLOWERUSERNAME, USERNAME),
    FOREIGN KEY(USERNAME) REFERENCES PERSON(USERNAME)
    ON DELETE CASCADE   
);

CREATE TABLE FOLLOWING (
    /*Who i'm following*/
    FOLLOWINGUSERNAME VARCHAR(20),
    /*Me*/
    USERNAME VARCHAR(20),
    PRIMARY KEY(FOLLOWINGUSERNAME, USERNAME),
    FOREIGN KEY(USERNAME) REFERENCES PERSON(USERNAME)
    ON DELETE CASCADE
);

CREATE TABLE POST (
    TWEETID INT AUTO_INCREMENT PRIMARY KEY,
    TWEET VARCHAR(140),
    TWEETDATE TIMESTAMP,
    USERNAME VARCHAR(20) NOT NULL,
    FOREIGN KEY(USERNAME) REFERENCES PERSON(USERNAME)
    ON DELETE CASCADE
);

CREATE TABLE HASHTAG (
    HASHTAGID INT AUTO_INCREMENT,
    TWEETID INT NOT NULL, 
    CONTENT VARCHAR(20),
    PRIMARY KEY(HASHTAGID, TWEETID),
    FOREIGN KEY(TWEETID) REFERENCES POST(TWEETID)
    ON DELETE CASCADE
);

/*
When PERSON 1 follow PERSON 2:
INSERT INTO FOLLOWING VALUES("PERSON2", "PERSON1"); -> PERSON 1 FOLLOW PERSON 2
INSERT INTO FOLLOWER VALUES("PERSON1", "PERSON2"); -> PERSON 2 IS FOLLOWED BY PERSON 1

When PERSON 1 is followed by PERSON 2:
INSERT INTO FOLLOWER VALUES("PERSON2", "PERSON1"); -> PERSON 1 IS FOLLOWED BY PERSON 2
*/

DROP TABLE HASHTAG;
DROP TABLE POST;
DROP TABLE FOLLOWER;
DROP TABLE FOLLOWING;
DROP TABLE PERSON;
DROP TABLE ADMIN;
DROP TABLE ACCOUNT;