@startuml

title __MODEL's Class Diagram__\n

  package Twitter {
    package Twitter.twitterstage {
      package Twitter.twitterstage.model {
        class Person {
            - name : String
            - image : Image
            - joinedDate : String
            - postList : List<Post>
            - globalPostList : List<Post>
            - followers : List<Person>
            - followings : List<Person>
            + getName()
            + getImage()
            + getJoinedDate()
            + getPostList()
            + getGlobalPostList()
            + getFollowers()
            + getFollowings()
            + setFollowers()
            + setFollowings()
            + setJoinedDate()
            + setPostList()
            + setGlobalPostList()
            + setName()
            + setImage()
            + toString()
            + removePost()
        }
      }
    }
  }
  

  package Twitter {
    package Twitter.twitterstage {
      package Twitter.twitterstage.model {
        class Post {
            - tweetID : Integer
            - whoTweeted : String
            - tweetText : String
            - hashTags : List<String>
            - dateTweeted : String
            + Post()
            + Post()
            + getTweetID()
            + getWhoTweeted()
            + getTweetText()
            + getHashTags()
            + getDateTweeted()
            + setTweetID()
            + setWhoTweeted()
            + setTweetText()
            + setHashTags()
            + setDateTweeted()
            + toString()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
